-- create tables
create table create_table_if_not_exists_cli (
    id                             number generated by default on null as identity 
                                   constraint create_table_if_no_id_pk primary key,
    id_int_not_null_auto_increment varchar2(4000 char),
    nombrevarchar225_not_null      varchar2(4000 char),
    apellidosvarchar225_not_null   varchar2(4000 char),
    documento_identidadvarchar28_n varchar2(4000 char),
    direccionvarchar2100_not_null  varchar2(4000 char),
    correovarchar250_character_set varchar2(4000 char),
    telefonovarchar225_null_defaul varchar2(4000 char),
    sexovarchar21_not_null         varchar2(4000 char),
    fecharegistro_datetime3_null_d date,
    fechamodificacion_datetime3_nu date,
    usuarioregistrovarchar225_null varchar2(4000 char),
    usuariomodificacionvarchar225_ varchar2(4000 char),
    activo_tinyint_not_null        varchar2(4000 char),
    primary_key_id                 varchar2(4000 char)
)
;

create table create_table_if_not_exists_cli (
    nombresvarchar225_not_null     varchar2(4000 char),
    telefonovarchar225_not_null    varchar2(4000 char)
)
;

create table create_table_if_not_exists_cli (
    medicoid_int_not_null          varchar2(4000 char),
    pacienteid_int_not_null        varchar2(4000 char),
    fechaatencion_date_not_null    date,
    inicioatencion_time_not_null   varchar2(4000 char),
    finatencion_time_not_null      varchar2(4000 char),
    estadovarchar225_not_null      varchar2(4000 char),
    observacionesvarchar2500_null_ varchar2(4000 char),
    fecharegistro_datetime3_not_nu date,
    index_fk_medicos_citas_medicoi varchar2(4000 char),
    index_fk_paciente_citas_pacien varchar2(4000 char)
)
;

create table constraint_fk_medicos_citas (
    id                             number generated by default on null as identity 
                                   constraint constraint_fk_medi_id_pk primary key,
    create_table_if_not_exists_cli number,
    foreign_key_medicoid           varchar2(4000 char),
    references_clinica_medicos_id  varchar2(4000 char)
)
;

create table constraint_fk_paciente_citas (
    id                             number generated by default on null as identity 
                                   constraint constraint_fk_paci_id_pk primary key,
    create_table_if_not_exists_cli number,
    foreign_key_pacienteid         varchar2(4000 char),
    references_clinica_paciente_id varchar2(4000 char)
)
;

create table create_table_if_not_exists_cli (
    nombrevarchar2100_not_null     varchar2(4000 char),
    descripcionvarchar2500_charact varchar2(4000 char)
)
;

create table create_table_if_not_exists_cli (
    index_fk_medicos_horarios_medi varchar2(4000 char)
)
;

create table constraint_fk_medicos_horarios (
    id                             number generated by default on null as identity 
                                   constraint constraint_fk_medi_id_pk primary key,
    create_table_if_not_exists_cli number,
    foreign_key_medicoid           varchar2(4000 char),
    references_clinica_medicos_id  varchar2(4000 char)
)
;

create table create_table_if_not_exists_cli (
    especialidadid_int_not_null    varchar2(4000 char),
    index_fk_especialidades_especi varchar2(4000 char),
    index_fk_medicos_medicoid_asc_ varchar2(4000 char)
)
;

create table constraint_fk_especialidades (
    id                             number generated by default on null as identity 
                                   constraint constraint_fk_espe_id_pk primary key,
    create_table_if_not_exists_cli number,
    foreign_key_especialidadid     varchar2(4000 char),
    references_dbo_especialidades_ varchar2(4000 char)
)
;

create table constraint_fk_medicos (
    id                             number generated by default on null as identity 
                                   constraint constraint_fk_medi_id_pk primary key,
    create_table_if_not_exists_cli number,
    foreign_key_medicoid           varchar2(4000 char),
    references_clinica_medicos_id  varchar2(4000 char)
)
;

-- load data
